name: Android One-Click Build

on:
  push:
    branches:
      - main  # 当你推送到 main 分支时自动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir -p $HOME/cmdline-tools
        unzip commandlinetools-linux-9477386_latest.zip -d $HOME/cmdline-tools
        export PATH=$HOME/cmdline-tools/cmdline-tools/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33"

    - name: Build project
      run: ./gradlew build
